import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Header from '../components/Header/Header'
import SearchBars from '../components/SearchBar/SearchBars'
import SideSelection from '../components/SideSelection/SideSelection'
import ListView from '../components/ListView/ListView'

export default function Home() {
    return (
        <div className={styles.container}>
            <Header title="Create Next App" description="Generated by create next app" favicon="/favicon.ico" />

            <main className={styles.main}>
                <h1 className={styles.title}>
                    Welcome to Github Query Apps
                </h1>

                <SearchBars />
                
        <div className={styles.grid}>
                <SideSelection />
                <ListView />

        </div>

            </main>
        </div>
    )
}
